--
-- PostgreSQL database dump
--

-- Dumped from database version 15.6
-- Dumped by pg_dump version 16.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: t_annotation_types; Type: TABLE DATA; Schema: pc; Owner: d3l243
--

COPY pc.t_annotation_types (annotation_type_id, type_name, description, example, authority_id) FROM stdin;
1	Locus	TIGR Locus	DR0001	1
2	Gene Symbol	NCBI Gene Symbol	dnaN	2
3	Common Name	NCBI Common Name	\N	2
6	GI Number	Genbank ID Number	gi|7471825	2
7	UniParc ID	UniProt Archive ID	Q9RYE8_DEIRA	8
8	UniProtKB/SwissProt	UniProt Knowledgebase/SwissProt	Q9RYE8_DEIRA	8
10	Accession Number	GenBank Accession Number	AAF09595.1	2
11	RefSeq ID	GenBank RefSeq	ref|YP_463220.1	2
12	PIR ID	Protein Information Resource ID	D75571	8
13	IPI Number	International Protein Index Number	IPI00015171	4
14	Other	Oddball things that don't really fit a major category	\N	6
16	IPR Number	Interpro IPR ID	IPR001001	17
17	Wormpep Accession	Wormpep Accession Number	CE00011	3
18	Mixed	Name contains multiple annotation types		7
19	Unspecified	Annotation source not specified or locally generated	RANI60000	7
20	CyanoBase ID	ID Number from CyanoBase	SGL0001	18
21	Contigs	Translated Contiguous Genome Sequences	Contig0.1_19_17904_15715	7
22	Locus	Locus ID from Joint Genomics Institute	dde_0001	16
23	Stop-to-Stop	Local Names from Stop-to-Stop database generation	ORF_0011	7
24	Poxpep ID	ID from Poxvirus Bioinformatics Research Center	MPXV-ZRE_023	14
25	Stop-to-Start	Proteins from Stop codon to next start codon		7
26	Local	Locally generated identification	Sama_0001	7
27	Locus Name	NCBI Gene Locus Name	pYV0001	2
28	Locus	Yeast Genome Database Locus	YAL001C	19
29	Accession Number	TAIR Accession	AT1G01010	20
30	Mixed	NCBI Annotations with mixed names	gi|78369655|ref|NP_001030383.1|	2
31	ENSEMBL	Protein description from ENSEMBL database		9
32	Sanger	Sequences from the Sanger Institute	LinJ01_0010	3
37	JGI - Ga	JGI Genome Annotation Project	Ga0590897_001_53_466	16
33	Trembl ID	Uniprot Trembl ID	tr|A2NTS4	8
34	Accession Number	MScDB Accession	MScDB:00000033	21
36	BROAD_Gene_number	bgene IDs generated by the BROAD Institute	NCU00003T0	22
\.


--
-- Name: t_annotation_types_annotation_type_id_seq; Type: SEQUENCE SET; Schema: pc; Owner: d3l243
--

SELECT pg_catalog.setval('pc.t_annotation_types_annotation_type_id_seq', 37, true);


--
-- PostgreSQL database dump complete
--

