--
-- Name: VW_PUB_RBAC_APPLICATION; Type: FOREIGN TABLE; Schema: pnnldata; Owner: d3l243
--

CREATE FOREIGN TABLE pnnldata."VW_PUB_RBAC_APPLICATION" (
    "RBAC_APPL_GUID" character varying(32) NOT NULL,
    "PARENT_RBAC_APPL_GUID" character varying(32),
    "RBAC_APPL_NAME" character varying(64) NOT NULL,
    "RBAC_APPL_DESC" character varying(2000),
    "DISPLAY_NAME" character varying(255),
    "OWNER_EMPLID" character varying(11),
    "CREATE_DTM" timestamp(3) without time zone NOT NULL,
    "MODIFIED_DTM" timestamp(3) without time zone NOT NULL,
    "IRI_APPL_ID" integer NOT NULL,
    "MODIFIED_USN" bigint,
    "DELETE_DTM" timestamp(3) without time zone,
    "DELETE_SW" character(1)
)
SERVER op_warehouse_fdw
OPTIONS (
    schema_name 'dbo',
    table_name 'VW_PUB_RBAC_APPLICATION'
);
ALTER FOREIGN TABLE pnnldata."VW_PUB_RBAC_APPLICATION" ALTER COLUMN "RBAC_APPL_GUID" OPTIONS (
    column_name 'RBAC_APPL_GUID'
);
ALTER FOREIGN TABLE pnnldata."VW_PUB_RBAC_APPLICATION" ALTER COLUMN "PARENT_RBAC_APPL_GUID" OPTIONS (
    column_name 'PARENT_RBAC_APPL_GUID'
);
ALTER FOREIGN TABLE pnnldata."VW_PUB_RBAC_APPLICATION" ALTER COLUMN "RBAC_APPL_NAME" OPTIONS (
    column_name 'RBAC_APPL_NAME'
);
ALTER FOREIGN TABLE pnnldata."VW_PUB_RBAC_APPLICATION" ALTER COLUMN "RBAC_APPL_DESC" OPTIONS (
    column_name 'RBAC_APPL_DESC'
);
ALTER FOREIGN TABLE pnnldata."VW_PUB_RBAC_APPLICATION" ALTER COLUMN "DISPLAY_NAME" OPTIONS (
    column_name 'DISPLAY_NAME'
);
ALTER FOREIGN TABLE pnnldata."VW_PUB_RBAC_APPLICATION" ALTER COLUMN "OWNER_EMPLID" OPTIONS (
    column_name 'OWNER_EMPLID'
);
ALTER FOREIGN TABLE pnnldata."VW_PUB_RBAC_APPLICATION" ALTER COLUMN "CREATE_DTM" OPTIONS (
    column_name 'CREATE_DTM'
);
ALTER FOREIGN TABLE pnnldata."VW_PUB_RBAC_APPLICATION" ALTER COLUMN "MODIFIED_DTM" OPTIONS (
    column_name 'MODIFIED_DTM'
);
ALTER FOREIGN TABLE pnnldata."VW_PUB_RBAC_APPLICATION" ALTER COLUMN "IRI_APPL_ID" OPTIONS (
    column_name 'IRI_APPL_ID'
);
ALTER FOREIGN TABLE pnnldata."VW_PUB_RBAC_APPLICATION" ALTER COLUMN "MODIFIED_USN" OPTIONS (
    column_name 'MODIFIED_USN'
);
ALTER FOREIGN TABLE pnnldata."VW_PUB_RBAC_APPLICATION" ALTER COLUMN "DELETE_DTM" OPTIONS (
    column_name 'DELETE_DTM'
);
ALTER FOREIGN TABLE pnnldata."VW_PUB_RBAC_APPLICATION" ALTER COLUMN "DELETE_SW" OPTIONS (
    column_name 'DELETE_SW'
);


ALTER FOREIGN TABLE pnnldata."VW_PUB_RBAC_APPLICATION" OWNER TO d3l243;

