--
-- Name: VW_ATS_BMI_DEPARTMENT; Type: FOREIGN TABLE; Schema: pnnldata; Owner: d3l243
--

CREATE FOREIGN TABLE pnnldata."VW_ATS_BMI_DEPARTMENT" (
    "DEPTID" character varying(10) NOT NULL,
    "ACTING_MGR_EMPLID" character varying(11),
    "COMPANY" character varying(3),
    "CURRENT_MGR_EMPLID" character varying(11),
    "DEPT_CD" character varying(7),
    "DEPTID_LEVEL" numeric(38,0) NOT NULL,
    "DESC30" character varying(30),
    "DESC10" character varying(10),
    "EFF_DATE" timestamp(3) without time zone,
    "EFF_STATUS" character varying(1) NOT NULL,
    "ESTABID" character varying(5),
    "MANAGER_EMPLID" character varying(11),
    "MANAGER_POSN" character varying(8),
    "COST_CD" character varying(6),
    "ORG_STRUC_ID" character varying(10),
    "ORGANIZATION_TYPE" character varying(1),
    "PARENT_DEPTID" character varying(10),
    "PARENT_NODE_NUM" numeric(38,0) NOT NULL,
    "SECRETARY_EMPLID" character varying(11),
    "SECRETARY_POSN" character varying(8),
    "SETID" character varying(5) NOT NULL,
    "SETID_LOCATION" character varying(5),
    "TREE_NODE_NUM" numeric(38,0) NOT NULL,
    "TREE_NODE_NUM_END" numeric(38,0) NOT NULL,
    "ORG_LEVEL" character varying(3),
    "DW_ACQ_DATETIME" timestamp(3) without time zone NOT NULL
)
SERVER op_warehouse_fdw
OPTIONS (
    schema_name 'dbo',
    table_name 'VW_ATS_BMI_DEPARTMENT'
);
ALTER FOREIGN TABLE pnnldata."VW_ATS_BMI_DEPARTMENT" ALTER COLUMN "DEPTID" OPTIONS (
    column_name 'DEPTID'
);
ALTER FOREIGN TABLE pnnldata."VW_ATS_BMI_DEPARTMENT" ALTER COLUMN "ACTING_MGR_EMPLID" OPTIONS (
    column_name 'ACTING_MGR_EMPLID'
);
ALTER FOREIGN TABLE pnnldata."VW_ATS_BMI_DEPARTMENT" ALTER COLUMN "COMPANY" OPTIONS (
    column_name 'COMPANY'
);
ALTER FOREIGN TABLE pnnldata."VW_ATS_BMI_DEPARTMENT" ALTER COLUMN "CURRENT_MGR_EMPLID" OPTIONS (
    column_name 'CURRENT_MGR_EMPLID'
);
ALTER FOREIGN TABLE pnnldata."VW_ATS_BMI_DEPARTMENT" ALTER COLUMN "DEPT_CD" OPTIONS (
    column_name 'DEPT_CD'
);
ALTER FOREIGN TABLE pnnldata."VW_ATS_BMI_DEPARTMENT" ALTER COLUMN "DEPTID_LEVEL" OPTIONS (
    column_name 'DEPTID_LEVEL'
);
ALTER FOREIGN TABLE pnnldata."VW_ATS_BMI_DEPARTMENT" ALTER COLUMN "DESC30" OPTIONS (
    column_name 'DESC30'
);
ALTER FOREIGN TABLE pnnldata."VW_ATS_BMI_DEPARTMENT" ALTER COLUMN "DESC10" OPTIONS (
    column_name 'DESC10'
);
ALTER FOREIGN TABLE pnnldata."VW_ATS_BMI_DEPARTMENT" ALTER COLUMN "EFF_DATE" OPTIONS (
    column_name 'EFF_DATE'
);
ALTER FOREIGN TABLE pnnldata."VW_ATS_BMI_DEPARTMENT" ALTER COLUMN "EFF_STATUS" OPTIONS (
    column_name 'EFF_STATUS'
);
ALTER FOREIGN TABLE pnnldata."VW_ATS_BMI_DEPARTMENT" ALTER COLUMN "ESTABID" OPTIONS (
    column_name 'ESTABID'
);
ALTER FOREIGN TABLE pnnldata."VW_ATS_BMI_DEPARTMENT" ALTER COLUMN "MANAGER_EMPLID" OPTIONS (
    column_name 'MANAGER_EMPLID'
);
ALTER FOREIGN TABLE pnnldata."VW_ATS_BMI_DEPARTMENT" ALTER COLUMN "MANAGER_POSN" OPTIONS (
    column_name 'MANAGER_POSN'
);
ALTER FOREIGN TABLE pnnldata."VW_ATS_BMI_DEPARTMENT" ALTER COLUMN "COST_CD" OPTIONS (
    column_name 'COST_CD'
);
ALTER FOREIGN TABLE pnnldata."VW_ATS_BMI_DEPARTMENT" ALTER COLUMN "ORG_STRUC_ID" OPTIONS (
    column_name 'ORG_STRUC_ID'
);
ALTER FOREIGN TABLE pnnldata."VW_ATS_BMI_DEPARTMENT" ALTER COLUMN "ORGANIZATION_TYPE" OPTIONS (
    column_name 'ORGANIZATION_TYPE'
);
ALTER FOREIGN TABLE pnnldata."VW_ATS_BMI_DEPARTMENT" ALTER COLUMN "PARENT_DEPTID" OPTIONS (
    column_name 'PARENT_DEPTID'
);
ALTER FOREIGN TABLE pnnldata."VW_ATS_BMI_DEPARTMENT" ALTER COLUMN "PARENT_NODE_NUM" OPTIONS (
    column_name 'PARENT_NODE_NUM'
);
ALTER FOREIGN TABLE pnnldata."VW_ATS_BMI_DEPARTMENT" ALTER COLUMN "SECRETARY_EMPLID" OPTIONS (
    column_name 'SECRETARY_EMPLID'
);
ALTER FOREIGN TABLE pnnldata."VW_ATS_BMI_DEPARTMENT" ALTER COLUMN "SECRETARY_POSN" OPTIONS (
    column_name 'SECRETARY_POSN'
);
ALTER FOREIGN TABLE pnnldata."VW_ATS_BMI_DEPARTMENT" ALTER COLUMN "SETID" OPTIONS (
    column_name 'SETID'
);
ALTER FOREIGN TABLE pnnldata."VW_ATS_BMI_DEPARTMENT" ALTER COLUMN "SETID_LOCATION" OPTIONS (
    column_name 'SETID_LOCATION'
);
ALTER FOREIGN TABLE pnnldata."VW_ATS_BMI_DEPARTMENT" ALTER COLUMN "TREE_NODE_NUM" OPTIONS (
    column_name 'TREE_NODE_NUM'
);
ALTER FOREIGN TABLE pnnldata."VW_ATS_BMI_DEPARTMENT" ALTER COLUMN "TREE_NODE_NUM_END" OPTIONS (
    column_name 'TREE_NODE_NUM_END'
);
ALTER FOREIGN TABLE pnnldata."VW_ATS_BMI_DEPARTMENT" ALTER COLUMN "ORG_LEVEL" OPTIONS (
    column_name 'ORG_LEVEL'
);
ALTER FOREIGN TABLE pnnldata."VW_ATS_BMI_DEPARTMENT" ALTER COLUMN "DW_ACQ_DATETIME" OPTIONS (
    column_name 'DW_ACQ_DATETIME'
);


ALTER FOREIGN TABLE pnnldata."VW_ATS_BMI_DEPARTMENT" OWNER TO d3l243;

--
-- Name: TABLE "VW_ATS_BMI_DEPARTMENT"; Type: ACL; Schema: pnnldata; Owner: d3l243
--

GRANT SELECT ON TABLE pnnldata."VW_ATS_BMI_DEPARTMENT" TO writeaccess;

