--
-- Name: VW_PUB_EQPT_GETSTATS; Type: FOREIGN TABLE; Schema: pnnldata; Owner: d3l243
--

CREATE FOREIGN TABLE pnnldata."VW_PUB_EQPT_GETSTATS" (
    "EQPT_GUID" character varying(50) NOT NULL,
    "ENTRY_DATE_TIME" timestamp(3) without time zone NOT NULL,
    "NETWORK_ID" character varying(32) NOT NULL,
    "NETWORK_DOMAIN" character varying(32) NOT NULL,
    "CPU_ID" character varying(25) NOT NULL,
    "CPU_QTY" integer NOT NULL,
    "MEMORY_MB" integer NOT NULL,
    "OS_NAME" character varying(50) NOT NULL,
    "OS_VERSION" character varying(50) NOT NULL,
    "DNS_NAME" character varying(32),
    "DNS_DOMAIN" character varying(50),
    "PING_ID" character varying(50) NOT NULL,
    "COMPUTER_NAME" character varying(32),
    "COMPUTER_NETWORK_DOMAIN" character varying(32),
    "COMPUTER_DOMAIN_TYPE" character varying(50),
    "MHP_IMAGE_VERSION" character varying(50),
    "MHP_IMAGE_REVISION" character varying(50),
    "PNNL_SETUP_PROPTY_NO" character varying(50),
    "PNNL_SETUP_RESP_EMPLID" character varying(50),
    "PNNL_SETUP_FACILITY_ID" character varying(50),
    "PNNL_SETUP_SPACE_ID" character varying(50),
    "PNNL_SETUP_RESP_NAME" character varying(50),
    "PLATFORM_NAME" character varying(10) NOT NULL,
    "FEED_VERSION" character varying(50) NOT NULL,
    "LAST_SEEN_DATE_TIME" timestamp(3) without time zone NOT NULL,
    "DEACT_DATETIME" timestamp(3) without time zone,
    "DELETE_DATETIME" timestamp(3) without time zone
)
SERVER op_warehouse_fdw
OPTIONS (
    schema_name 'dbo',
    table_name 'VW_PUB_EQPT_GETSTATS'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_EQPT_GETSTATS" ALTER COLUMN "EQPT_GUID" OPTIONS (
    column_name 'EQPT_GUID'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_EQPT_GETSTATS" ALTER COLUMN "ENTRY_DATE_TIME" OPTIONS (
    column_name 'ENTRY_DATE_TIME'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_EQPT_GETSTATS" ALTER COLUMN "NETWORK_ID" OPTIONS (
    column_name 'NETWORK_ID'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_EQPT_GETSTATS" ALTER COLUMN "NETWORK_DOMAIN" OPTIONS (
    column_name 'NETWORK_DOMAIN'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_EQPT_GETSTATS" ALTER COLUMN "CPU_ID" OPTIONS (
    column_name 'CPU_ID'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_EQPT_GETSTATS" ALTER COLUMN "CPU_QTY" OPTIONS (
    column_name 'CPU_QTY'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_EQPT_GETSTATS" ALTER COLUMN "MEMORY_MB" OPTIONS (
    column_name 'MEMORY_MB'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_EQPT_GETSTATS" ALTER COLUMN "OS_NAME" OPTIONS (
    column_name 'OS_NAME'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_EQPT_GETSTATS" ALTER COLUMN "OS_VERSION" OPTIONS (
    column_name 'OS_VERSION'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_EQPT_GETSTATS" ALTER COLUMN "DNS_NAME" OPTIONS (
    column_name 'DNS_NAME'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_EQPT_GETSTATS" ALTER COLUMN "DNS_DOMAIN" OPTIONS (
    column_name 'DNS_DOMAIN'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_EQPT_GETSTATS" ALTER COLUMN "PING_ID" OPTIONS (
    column_name 'PING_ID'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_EQPT_GETSTATS" ALTER COLUMN "COMPUTER_NAME" OPTIONS (
    column_name 'COMPUTER_NAME'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_EQPT_GETSTATS" ALTER COLUMN "COMPUTER_NETWORK_DOMAIN" OPTIONS (
    column_name 'COMPUTER_NETWORK_DOMAIN'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_EQPT_GETSTATS" ALTER COLUMN "COMPUTER_DOMAIN_TYPE" OPTIONS (
    column_name 'COMPUTER_DOMAIN_TYPE'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_EQPT_GETSTATS" ALTER COLUMN "MHP_IMAGE_VERSION" OPTIONS (
    column_name 'MHP_IMAGE_VERSION'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_EQPT_GETSTATS" ALTER COLUMN "MHP_IMAGE_REVISION" OPTIONS (
    column_name 'MHP_IMAGE_REVISION'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_EQPT_GETSTATS" ALTER COLUMN "PNNL_SETUP_PROPTY_NO" OPTIONS (
    column_name 'PNNL_SETUP_PROPTY_NO'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_EQPT_GETSTATS" ALTER COLUMN "PNNL_SETUP_RESP_EMPLID" OPTIONS (
    column_name 'PNNL_SETUP_RESP_EMPLID'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_EQPT_GETSTATS" ALTER COLUMN "PNNL_SETUP_FACILITY_ID" OPTIONS (
    column_name 'PNNL_SETUP_FACILITY_ID'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_EQPT_GETSTATS" ALTER COLUMN "PNNL_SETUP_SPACE_ID" OPTIONS (
    column_name 'PNNL_SETUP_SPACE_ID'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_EQPT_GETSTATS" ALTER COLUMN "PNNL_SETUP_RESP_NAME" OPTIONS (
    column_name 'PNNL_SETUP_RESP_NAME'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_EQPT_GETSTATS" ALTER COLUMN "PLATFORM_NAME" OPTIONS (
    column_name 'PLATFORM_NAME'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_EQPT_GETSTATS" ALTER COLUMN "FEED_VERSION" OPTIONS (
    column_name 'FEED_VERSION'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_EQPT_GETSTATS" ALTER COLUMN "LAST_SEEN_DATE_TIME" OPTIONS (
    column_name 'LAST_SEEN_DATE_TIME'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_EQPT_GETSTATS" ALTER COLUMN "DEACT_DATETIME" OPTIONS (
    column_name 'DEACT_DATETIME'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_EQPT_GETSTATS" ALTER COLUMN "DELETE_DATETIME" OPTIONS (
    column_name 'DELETE_DATETIME'
);


ALTER FOREIGN TABLE pnnldata."VW_PUB_EQPT_GETSTATS" OWNER TO d3l243;

--
-- Name: TABLE "VW_PUB_EQPT_GETSTATS"; Type: ACL; Schema: pnnldata; Owner: d3l243
--

GRANT SELECT ON TABLE pnnldata."VW_PUB_EQPT_GETSTATS" TO writeaccess;

