--
-- Name: VW_PUB_PROPERTY_ACCTG; Type: FOREIGN TABLE; Schema: pnnldata; Owner: d3l243
--

CREATE FOREIGN TABLE pnnldata."VW_PUB_PROPERTY_ACCTG" (
    "PROPTY_NO" character varying(9) NOT NULL,
    "ENT" character varying(1),
    "RETR_DATE" timestamp(3) without time zone,
    "CUSTD_CD" character varying(6),
    "GL_ACCT" character varying(5),
    "GL_FUND_TYPE" character varying(2),
    "GL_SUBACCT" character varying(8),
    "STATUS_CD" character varying(2),
    "ASSET_TYPE" character varying(3),
    "USEFUL_LIFE_YRS" numeric(38,0),
    "USEFUL_LIFE_MOS" numeric(38,0),
    "BARE_COST_IN_SERV_DATE" timestamp(3) without time zone,
    "BARE_COST" numeric(38,2),
    "BARE_COST_DEP" numeric(38,2),
    "INSTALLED_COST_IN_SERV_DATE" character varying(9),
    "INSTALLED_COST" numeric(38,2),
    "INSTALLED_COST_DEP" numeric(38,2),
    "TOTAL_COST" numeric(38,2),
    "TOTAL_DEP" numeric(38,2),
    "CM_DEP" numeric(38,2),
    "CY_DEP" numeric(38,2),
    "FIRE_REPLACEMENT_COST" numeric(38,2),
    "FY_DEP" character varying(20),
    "FY_DEP_ADJ" character varying(10),
    "MEMO_COST" character varying(10),
    "USE_TAX_BASE" character varying(10),
    "USE_TAX_ACCUM_DEP" character varying(10),
    "TAX_IND" character varying(1),
    "CLOSED_WIP_DATE" character varying(8),
    "ACQ_DATE" timestamp(3) without time zone,
    "ACQ_VOUCHER" character varying(11),
    "CONTRA_PROPTY_NO" character varying(9),
    "RPIS_CONTROL_NO" character varying(8),
    "DW_ACQ_DATETIME" timestamp(3) without time zone NOT NULL
)
SERVER op_warehouse_fdw
OPTIONS (
    schema_name 'dbo',
    table_name 'VW_PUB_PROPERTY_ACCTG'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_PROPERTY_ACCTG" ALTER COLUMN "PROPTY_NO" OPTIONS (
    column_name 'PROPTY_NO'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_PROPERTY_ACCTG" ALTER COLUMN "ENT" OPTIONS (
    column_name 'ENT'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_PROPERTY_ACCTG" ALTER COLUMN "RETR_DATE" OPTIONS (
    column_name 'RETR_DATE'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_PROPERTY_ACCTG" ALTER COLUMN "CUSTD_CD" OPTIONS (
    column_name 'CUSTD_CD'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_PROPERTY_ACCTG" ALTER COLUMN "GL_ACCT" OPTIONS (
    column_name 'GL_ACCT'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_PROPERTY_ACCTG" ALTER COLUMN "GL_FUND_TYPE" OPTIONS (
    column_name 'GL_FUND_TYPE'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_PROPERTY_ACCTG" ALTER COLUMN "GL_SUBACCT" OPTIONS (
    column_name 'GL_SUBACCT'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_PROPERTY_ACCTG" ALTER COLUMN "STATUS_CD" OPTIONS (
    column_name 'STATUS_CD'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_PROPERTY_ACCTG" ALTER COLUMN "ASSET_TYPE" OPTIONS (
    column_name 'ASSET_TYPE'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_PROPERTY_ACCTG" ALTER COLUMN "USEFUL_LIFE_YRS" OPTIONS (
    column_name 'USEFUL_LIFE_YRS'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_PROPERTY_ACCTG" ALTER COLUMN "USEFUL_LIFE_MOS" OPTIONS (
    column_name 'USEFUL_LIFE_MOS'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_PROPERTY_ACCTG" ALTER COLUMN "BARE_COST_IN_SERV_DATE" OPTIONS (
    column_name 'BARE_COST_IN_SERV_DATE'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_PROPERTY_ACCTG" ALTER COLUMN "BARE_COST" OPTIONS (
    column_name 'BARE_COST'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_PROPERTY_ACCTG" ALTER COLUMN "BARE_COST_DEP" OPTIONS (
    column_name 'BARE_COST_DEP'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_PROPERTY_ACCTG" ALTER COLUMN "INSTALLED_COST_IN_SERV_DATE" OPTIONS (
    column_name 'INSTALLED_COST_IN_SERV_DATE'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_PROPERTY_ACCTG" ALTER COLUMN "INSTALLED_COST" OPTIONS (
    column_name 'INSTALLED_COST'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_PROPERTY_ACCTG" ALTER COLUMN "INSTALLED_COST_DEP" OPTIONS (
    column_name 'INSTALLED_COST_DEP'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_PROPERTY_ACCTG" ALTER COLUMN "TOTAL_COST" OPTIONS (
    column_name 'TOTAL_COST'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_PROPERTY_ACCTG" ALTER COLUMN "TOTAL_DEP" OPTIONS (
    column_name 'TOTAL_DEP'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_PROPERTY_ACCTG" ALTER COLUMN "CM_DEP" OPTIONS (
    column_name 'CM_DEP'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_PROPERTY_ACCTG" ALTER COLUMN "CY_DEP" OPTIONS (
    column_name 'CY_DEP'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_PROPERTY_ACCTG" ALTER COLUMN "FIRE_REPLACEMENT_COST" OPTIONS (
    column_name 'FIRE_REPLACEMENT_COST'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_PROPERTY_ACCTG" ALTER COLUMN "FY_DEP" OPTIONS (
    column_name 'FY_DEP'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_PROPERTY_ACCTG" ALTER COLUMN "FY_DEP_ADJ" OPTIONS (
    column_name 'FY_DEP_ADJ'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_PROPERTY_ACCTG" ALTER COLUMN "MEMO_COST" OPTIONS (
    column_name 'MEMO_COST'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_PROPERTY_ACCTG" ALTER COLUMN "USE_TAX_BASE" OPTIONS (
    column_name 'USE_TAX_BASE'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_PROPERTY_ACCTG" ALTER COLUMN "USE_TAX_ACCUM_DEP" OPTIONS (
    column_name 'USE_TAX_ACCUM_DEP'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_PROPERTY_ACCTG" ALTER COLUMN "TAX_IND" OPTIONS (
    column_name 'TAX_IND'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_PROPERTY_ACCTG" ALTER COLUMN "CLOSED_WIP_DATE" OPTIONS (
    column_name 'CLOSED_WIP_DATE'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_PROPERTY_ACCTG" ALTER COLUMN "ACQ_DATE" OPTIONS (
    column_name 'ACQ_DATE'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_PROPERTY_ACCTG" ALTER COLUMN "ACQ_VOUCHER" OPTIONS (
    column_name 'ACQ_VOUCHER'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_PROPERTY_ACCTG" ALTER COLUMN "CONTRA_PROPTY_NO" OPTIONS (
    column_name 'CONTRA_PROPTY_NO'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_PROPERTY_ACCTG" ALTER COLUMN "RPIS_CONTROL_NO" OPTIONS (
    column_name 'RPIS_CONTROL_NO'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_PROPERTY_ACCTG" ALTER COLUMN "DW_ACQ_DATETIME" OPTIONS (
    column_name 'DW_ACQ_DATETIME'
);


ALTER FOREIGN TABLE pnnldata."VW_PUB_PROPERTY_ACCTG" OWNER TO d3l243;

--
-- Name: TABLE "VW_PUB_PROPERTY_ACCTG"; Type: ACL; Schema: pnnldata; Owner: d3l243
--

GRANT SELECT ON TABLE pnnldata."VW_PUB_PROPERTY_ACCTG" TO writeaccess;

