--
-- Name: VW_PUB_BMI_EMPLOYEE; Type: FOREIGN TABLE; Schema: pnnldata; Owner: d3l243
--

CREATE FOREIGN TABLE pnnldata."VW_PUB_BMI_EMPLOYEE" (
    "EMPLID" character varying(11) NOT NULL,
    "PNNL_PAY_NO" character varying(5),
    "HANFORD_ID" character varying(7),
    "ACTIVE_SW" character varying(1) NOT NULL,
    "ASGN_CORE_CAPABILITY" character varying(6),
    "BARG_UNIT_SW" character varying(4),
    "BUSINESS_TITLE" character varying(30),
    "COCS_CD" character varying(8),
    "COMPANY" character varying(3) NOT NULL,
    "CONTACT_LOCATION" character varying(10),
    "CONTACT_BLD_NO" character varying(11),
    "CONTACT_ROOM_NO" character varying(5),
    "CONTACT_MSIN" character varying(8),
    "CONTACT_BMI_MSIN" character varying(28),
    "CONTACT_FLOOR" character varying(10),
    "CONTACT_COUNTRY_CD" character varying(3),
    "CONTACT_WORK_PHONE" character varying(24),
    "COR_CD" character varying(11),
    "COR_AMOUNT" numeric(14,2),
    "COST_CD" character varying(6),
    "DEPTID" character varying(10) NOT NULL,
    "DEPT_CD" character varying(7),
    "FIRST_NAME" character varying(30) NOT NULL,
    "FULL_PART_TIME" character varying(1) NOT NULL,
    "INTERNET_EMAIL_ADDRESS" character varying(64),
    "LAST_NAME" character varying(30) NOT NULL,
    "MIDDLE_INITIAL" character varying(3),
    "NAME" character varying(50) NOT NULL,
    "NAME_PREFIX" character varying(4),
    "NAME_SUFFIX" character varying(15),
    "NETWORK_ID" character varying(32),
    "NETWORK_DOMAIN" character varying(32),
    "OFF_SPACE_OCCUPIED_SW" character varying(1),
    "PAYGROUP" character varying(3),
    "PER_STATUS" character varying(1) NOT NULL,
    "PER_TYPE" character varying(1),
    "POSITION_NO" character varying(8),
    "PREF_FIRST_NAME" character varying(30) NOT NULL,
    "PREF_LAST_NAME" character varying(30) NOT NULL,
    "PREF_MIDDLE_INIT" character varying(3),
    "PREFERRED_NAME" character varying(50) NOT NULL,
    "PREFERRED_NAME_FM" character varying(50),
    "PRIMARY_AREA" character varying(6),
    "PRIMARY_LOCATION" character varying(10) NOT NULL,
    "PRIMARY_BLD_NO" character varying(11),
    "PRIMARY_ROOM_NO" character varying(5),
    "PRIMARY_MSIN" character varying(8),
    "PRIMARY_BMI_MSIN" character varying(28),
    "PRIMARY_FLOOR" character varying(10),
    "PRIMARY_COUNTRY_CD" character varying(3),
    "PRIMARY_WORK_PHONE" character varying(24),
    "FAX_COUNTRY_CD" character varying(3),
    "FAX_NO" character varying(24),
    "REPORTING_MGR_EMPLID" character varying(11),
    "REPORTING_ORG_ID" character varying(10),
    "TYPE" character varying(1)
)
SERVER op_warehouse_fdw
OPTIONS (
    schema_name 'dbo',
    table_name 'VW_PUB_BMI_EMPLOYEE'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "EMPLID" OPTIONS (
    column_name 'EMPLID'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "PNNL_PAY_NO" OPTIONS (
    column_name 'PNNL_PAY_NO'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "HANFORD_ID" OPTIONS (
    column_name 'HANFORD_ID'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "ACTIVE_SW" OPTIONS (
    column_name 'ACTIVE_SW'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "ASGN_CORE_CAPABILITY" OPTIONS (
    column_name 'ASGN_CORE_CAPABILITY'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "BARG_UNIT_SW" OPTIONS (
    column_name 'BARG_UNIT_SW'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "BUSINESS_TITLE" OPTIONS (
    column_name 'BUSINESS_TITLE'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "COCS_CD" OPTIONS (
    column_name 'COCS_CD'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "COMPANY" OPTIONS (
    column_name 'COMPANY'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "CONTACT_LOCATION" OPTIONS (
    column_name 'CONTACT_LOCATION'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "CONTACT_BLD_NO" OPTIONS (
    column_name 'CONTACT_BLD_NO'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "CONTACT_ROOM_NO" OPTIONS (
    column_name 'CONTACT_ROOM_NO'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "CONTACT_MSIN" OPTIONS (
    column_name 'CONTACT_MSIN'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "CONTACT_BMI_MSIN" OPTIONS (
    column_name 'CONTACT_BMI_MSIN'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "CONTACT_FLOOR" OPTIONS (
    column_name 'CONTACT_FLOOR'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "CONTACT_COUNTRY_CD" OPTIONS (
    column_name 'CONTACT_COUNTRY_CD'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "CONTACT_WORK_PHONE" OPTIONS (
    column_name 'CONTACT_WORK_PHONE'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "COR_CD" OPTIONS (
    column_name 'COR_CD'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "COR_AMOUNT" OPTIONS (
    column_name 'COR_AMOUNT'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "COST_CD" OPTIONS (
    column_name 'COST_CD'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "DEPTID" OPTIONS (
    column_name 'DEPTID'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "DEPT_CD" OPTIONS (
    column_name 'DEPT_CD'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "FIRST_NAME" OPTIONS (
    column_name 'FIRST_NAME'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "FULL_PART_TIME" OPTIONS (
    column_name 'FULL_PART_TIME'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "INTERNET_EMAIL_ADDRESS" OPTIONS (
    column_name 'INTERNET_EMAIL_ADDRESS'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "LAST_NAME" OPTIONS (
    column_name 'LAST_NAME'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "MIDDLE_INITIAL" OPTIONS (
    column_name 'MIDDLE_INITIAL'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "NAME" OPTIONS (
    column_name 'NAME'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "NAME_PREFIX" OPTIONS (
    column_name 'NAME_PREFIX'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "NAME_SUFFIX" OPTIONS (
    column_name 'NAME_SUFFIX'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "NETWORK_ID" OPTIONS (
    column_name 'NETWORK_ID'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "NETWORK_DOMAIN" OPTIONS (
    column_name 'NETWORK_DOMAIN'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "OFF_SPACE_OCCUPIED_SW" OPTIONS (
    column_name 'OFF_SPACE_OCCUPIED_SW'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "PAYGROUP" OPTIONS (
    column_name 'PAYGROUP'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "PER_STATUS" OPTIONS (
    column_name 'PER_STATUS'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "PER_TYPE" OPTIONS (
    column_name 'PER_TYPE'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "POSITION_NO" OPTIONS (
    column_name 'POSITION_NO'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "PREF_FIRST_NAME" OPTIONS (
    column_name 'PREF_FIRST_NAME'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "PREF_LAST_NAME" OPTIONS (
    column_name 'PREF_LAST_NAME'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "PREF_MIDDLE_INIT" OPTIONS (
    column_name 'PREF_MIDDLE_INIT'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "PREFERRED_NAME" OPTIONS (
    column_name 'PREFERRED_NAME'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "PREFERRED_NAME_FM" OPTIONS (
    column_name 'PREFERRED_NAME_FM'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "PRIMARY_AREA" OPTIONS (
    column_name 'PRIMARY_AREA'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "PRIMARY_LOCATION" OPTIONS (
    column_name 'PRIMARY_LOCATION'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "PRIMARY_BLD_NO" OPTIONS (
    column_name 'PRIMARY_BLD_NO'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "PRIMARY_ROOM_NO" OPTIONS (
    column_name 'PRIMARY_ROOM_NO'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "PRIMARY_MSIN" OPTIONS (
    column_name 'PRIMARY_MSIN'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "PRIMARY_BMI_MSIN" OPTIONS (
    column_name 'PRIMARY_BMI_MSIN'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "PRIMARY_FLOOR" OPTIONS (
    column_name 'PRIMARY_FLOOR'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "PRIMARY_COUNTRY_CD" OPTIONS (
    column_name 'PRIMARY_COUNTRY_CD'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "PRIMARY_WORK_PHONE" OPTIONS (
    column_name 'PRIMARY_WORK_PHONE'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "FAX_COUNTRY_CD" OPTIONS (
    column_name 'FAX_COUNTRY_CD'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "FAX_NO" OPTIONS (
    column_name 'FAX_NO'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "REPORTING_MGR_EMPLID" OPTIONS (
    column_name 'REPORTING_MGR_EMPLID'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "REPORTING_ORG_ID" OPTIONS (
    column_name 'REPORTING_ORG_ID'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_BMI_EMPLOYEE" ALTER COLUMN "TYPE" OPTIONS (
    column_name 'TYPE'
);


ALTER FOREIGN TABLE pnnldata."VW_PUB_BMI_EMPLOYEE" OWNER TO d3l243;

--
-- Name: TABLE "VW_PUB_BMI_EMPLOYEE"; Type: ACL; Schema: pnnldata; Owner: d3l243
--

GRANT SELECT ON TABLE pnnldata."VW_PUB_BMI_EMPLOYEE" TO writeaccess;

