--
-- Name: VW_PUB_MANAGEMENT_SYSTEM; Type: FOREIGN TABLE; Schema: pnnldata; Owner: d3l243
--

CREATE FOREIGN TABLE pnnldata."VW_PUB_MANAGEMENT_SYSTEM" (
    "MGMT_SYS_CD" numeric(38,0) NOT NULL,
    "MGMT_SYS_TITLE" character varying(200) NOT NULL,
    "MGMT_SYS_OWNER_EMPLID" character varying(11),
    "POC_EMPLID" character varying(11),
    "DATE_CREATED" timestamp(3) without time zone,
    "DATE_MODIFIED" timestamp(3) without time zone,
    "ACTIVE_SW" character varying(1)
)
SERVER op_warehouse_fdw
OPTIONS (
    schema_name 'dbo',
    table_name 'VW_PUB_MANAGEMENT_SYSTEM'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_MANAGEMENT_SYSTEM" ALTER COLUMN "MGMT_SYS_CD" OPTIONS (
    column_name 'MGMT_SYS_CD'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_MANAGEMENT_SYSTEM" ALTER COLUMN "MGMT_SYS_TITLE" OPTIONS (
    column_name 'MGMT_SYS_TITLE'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_MANAGEMENT_SYSTEM" ALTER COLUMN "MGMT_SYS_OWNER_EMPLID" OPTIONS (
    column_name 'MGMT_SYS_OWNER_EMPLID'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_MANAGEMENT_SYSTEM" ALTER COLUMN "POC_EMPLID" OPTIONS (
    column_name 'POC_EMPLID'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_MANAGEMENT_SYSTEM" ALTER COLUMN "DATE_CREATED" OPTIONS (
    column_name 'DATE_CREATED'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_MANAGEMENT_SYSTEM" ALTER COLUMN "DATE_MODIFIED" OPTIONS (
    column_name 'DATE_MODIFIED'
);
ALTER FOREIGN TABLE ONLY pnnldata."VW_PUB_MANAGEMENT_SYSTEM" ALTER COLUMN "ACTIVE_SW" OPTIONS (
    column_name 'ACTIVE_SW'
);


ALTER FOREIGN TABLE pnnldata."VW_PUB_MANAGEMENT_SYSTEM" OWNER TO d3l243;

--
-- Name: TABLE "VW_PUB_MANAGEMENT_SYSTEM"; Type: ACL; Schema: pnnldata; Owner: d3l243
--

GRANT SELECT ON TABLE pnnldata."VW_PUB_MANAGEMENT_SYSTEM" TO writeaccess;

