--
-- Name: VW_PUB_SMS_NETWORK_INTERFACE; Type: FOREIGN TABLE; Schema: pnnldata; Owner: d3l243
--

CREATE FOREIGN TABLE pnnldata."VW_PUB_SMS_NETWORK_INTERFACE" (
    "SMS_DEVICE_ID" integer NOT NULL,
    "DHCP_SERVER_IP_ADDRESS" character varying(15) NOT NULL,
    "GATEWAY_IP_ADDRESS" character varying(15) NOT NULL,
    "SMS_INTERFACE_NAME" character varying(255),
    "PHYSICAL_ADDRESS" character varying(32),
    "LAST_SEEN_DTM" timestamp(3) without time zone,
    "DW_ACQ_DATETIME" timestamp(3) without time zone
)
SERVER op_warehouse_fdw
OPTIONS (
    schema_name 'dbo',
    table_name 'VW_PUB_SMS_NETWORK_INTERFACE'
);
ALTER FOREIGN TABLE pnnldata."VW_PUB_SMS_NETWORK_INTERFACE" ALTER COLUMN "SMS_DEVICE_ID" OPTIONS (
    column_name 'SMS_DEVICE_ID'
);
ALTER FOREIGN TABLE pnnldata."VW_PUB_SMS_NETWORK_INTERFACE" ALTER COLUMN "DHCP_SERVER_IP_ADDRESS" OPTIONS (
    column_name 'DHCP_SERVER_IP_ADDRESS'
);
ALTER FOREIGN TABLE pnnldata."VW_PUB_SMS_NETWORK_INTERFACE" ALTER COLUMN "GATEWAY_IP_ADDRESS" OPTIONS (
    column_name 'GATEWAY_IP_ADDRESS'
);
ALTER FOREIGN TABLE pnnldata."VW_PUB_SMS_NETWORK_INTERFACE" ALTER COLUMN "SMS_INTERFACE_NAME" OPTIONS (
    column_name 'SMS_INTERFACE_NAME'
);
ALTER FOREIGN TABLE pnnldata."VW_PUB_SMS_NETWORK_INTERFACE" ALTER COLUMN "PHYSICAL_ADDRESS" OPTIONS (
    column_name 'PHYSICAL_ADDRESS'
);
ALTER FOREIGN TABLE pnnldata."VW_PUB_SMS_NETWORK_INTERFACE" ALTER COLUMN "LAST_SEEN_DTM" OPTIONS (
    column_name 'LAST_SEEN_DTM'
);
ALTER FOREIGN TABLE pnnldata."VW_PUB_SMS_NETWORK_INTERFACE" ALTER COLUMN "DW_ACQ_DATETIME" OPTIONS (
    column_name 'DW_ACQ_DATETIME'
);


ALTER FOREIGN TABLE pnnldata."VW_PUB_SMS_NETWORK_INTERFACE" OWNER TO d3l243;

