CREATE OR REPLACE PROCEDURE pc.update_protein_sequence_info
(
    _proteinID int,
    _sequence text,
    _length int,
    _molecularFormula text,
    _monoisotopicMass float8,
    _averageMass float8,
    _sha1Hash text,
    INOUT _message text default '',
    INOUT _returnCode text default ''
)
LANGUAGE plpgsql
AS $$
/****************************************************
**
**  Desc:
**      Update an existing protein
**
**  Auth:   kja
**  Date:   10/06/2004
**          05/01/2023 mem - Ported to PostgreSQL
**
*****************************************************/
DECLARE
    _tmpHash text;
BEGIN

    _message := '';
    _returnCode := '';

    ---------------------------------------------------
    -- Does entry already exist?
    ---------------------------------------------------

    SELECT sha1_hash
    INTO _tmpHash
    FROM pc.t_proteins
    WHERE protein_id = _proteinID;

    If Not FOUND Then
        _message := format('Protein ID %s not found', _proteinID);
        RAISE WARNING '%', _message;
        _returnCode := 'U5001';
        RETURN;
    End If;

    ---------------------------------------------------
    -- Action for update mode
    ---------------------------------------------------

    UPDATE pc.t_proteins
    SET "sequence" = _sequence,
        length = _length,
        molecular_formula = _molecularFormula,
        monoisotopic_mass = _monoisotopicMass,
        average_mass = _averageMass,
        sha1_hash = _sha1Hash,
        date_modified = CURRENT_TIMESTAMP
    WHERE protein_id = _proteinID;

END
$$;

COMMENT ON PROCEDURE pc.update_protein_sequence_info IS 'UpdateProteinSequenceInfo';


select * from pc.t_proteins where protein_id=117057175;

call pc.update_protein_sequence_info(117057175,
'MLLQRRSWLWLYIRIGVILGDILGRKPSIREQHGGNSCYQLNRLFCDFQEADNYCHAQRGRLAHTWNPKLRGFLKSFLNEETVWWVRGNLTLPGSHPGINQTGGDDVLRNQKPGECPSVVTHSNAVFSRWNLCIEKHHFICQAAAFPPQGASIWRNEFGPGPLLPMKRRGAETERHMIPGNGPPLAMCHQPAPPELFETLCFPIDPASSAPPKATHRMTITSLTGRPQVTSDTLASSSPPQGTSDTPASSSPPQVTSATSASSSPPQGTSDTPASSSPPQVTSATSASSSPPQGTSDTPASSSPPQVTSATSASSSPPQGTSDTPASSSPPQVTSATSASSSPPQGTSDTPASSSPPQGTLDTPSSSSPPQGTSDTPASSSPPQGTSETPASNSPPQGTSETPGFSSPPQVTTATLVSSSPPQVTSETPASSSPTQVTSETPASSSPTQVTSDTPASNSPPQGTSDTPGFSSPTQVTTATLVSSSPPQVTSDTPASSSPPQVTSDTPASSSPPQVTSETPASSSPPQVTSDTSASISPPQVISDTPASSSPPQVTSETPASSSPTNMTSDTPASSSPTNMTSDTPASSSPTNMTSDTPASSSPPWPVITEVTRPESTIPAGRSLANITSKAQEDSPLGVISTHPQMSFQSSTSQALDETAGERVPTIPDFQAHSEFQKACAILQRLRDFLPTSPTSAQKNNSWSSQTPAVSCPFQPLGRLTTTEKSSHQMAQQDMEQHPMDGAHNAFGISAGGSEIQSDIQLRSEFEVEDMLETSLMALGEIHRAFCQQSLCPQSAVTLASPSATLMLSSQNVSTLPLSTYTLGEPAPLTLGFPSAEALKELLNKHPGVNLQVTGLAFNPFKTLDDKNIVGSIGNVQLSSAYQSIRVHDLIEDIEIMLWRNASMETQPTSLNTSTDHFTISVNITSLEKTLIVTIEPESPLLMTLHLGFQDQLAHTHFYLNISLPRDQVWQKDEEYTWVLTPENLWYGTGTYYIMAVENKSTEAAQHTPVLVSVVTAVTQCYFWDRYNRTWKSDGCQVGPKSTILKTQCLCDHLTFFSSDFFIVPRTVDVENTIKLLLHVTNNPVGVSLLSSLLGFYILLAMWASRKDREDMQKVKVTVLADNDPSSASHYLIQVYTGYRRRAATTAKVVITLYGSEGHSEPHHLCDPEKTVFERGALDVFLLSTGSWLGDLHGLRLWHDNSGDSPSWYVSQVIVSDMTTRKKWHFQCNCWLAVDLGNCERDRVFTPASRSELSSFRHLFSSTIVEKFTQDYLWLSVATRHPWNQFTRVQRLSCCMALLLCDMVINIMFWKMGGTTAKRGTEQLGPLAVTLSELLVSIQTSIILFPIHLIFGRLFQLIHPPEALPQLPFIQAAWPPALVCESPSLTQVVKELKETVGFLLRRNTQLLSECEPSSCSSCDINKLAKLLSGLIYCHLEDEGCHQQTESHWEDAVSENHYHFCRYLLQLLRRLKAHLEALGATQDHQSCDFSEAVSQLQNLQELLETQTLRRGPGPCRHSTSFPILSPGEGKKPMSFCLFRWLKCSCWLLLGVISLASAFFITLYSLELDKDQATSWVISMMLSVLQDIFISQPIKVIFLTLLFSLMANHMPWLNKDKEQHARRIVALWAKCPWSAPGLRDKNNPIYTAPAMNNLAKPTRKAWKKQLSKLTGGTLVQILFLTLLMTTVYSAKDSSRFFLHRAIWKRFSHRFSEIKTVEDFYPWANGTLLPNLYGDYRGFITDGNSFLLGNVLIRQTRIPNDIFFPGSLHKQMKSPPQHQEDRENYGAGWVPPDTNITKVDSIWHYQNQESLGGYPIQGELATYSGGGYVVRLGRNHSAATRVLQHLEQRRWLDHCTKALFVEFTVFNANVNLLCAVTLILESSGVGTFLTSLQLDSLTSLQSSERGFAWIVSQVVYYLLVCYYAFIQGCRLKRQRLAFFTRKRNLLDTSIVLISFSILGLSMQSLSLLHKKMQQYHCDRDRFISFYEALRVNSAVTHLRGFLLLFATVRVWDLLRHHAQLQVINKTLSKAWDEVLGFILIIVVLLSSYAMTFNLLFGWSISDYQSFFRSIVTVVGLLMGTSKHKEVIALYPILGSLLVLSSIILMGLVIINLFVSAILIAFGKERKACEKEATLTDMLLQKLSSLLGIRLHQNPSEEHADNTGSSNLRERSSKSMSSDAEVLAPADAVGSVSGTDGNSGSTKGTRDI'::text,
2204, 'C10716 H16770 N2914 O3281 S83', 241431.168379233, 241585.647391234, '6D49471D322E5A52827187B994AD356AA16B3C4C')

