--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: mc; Owner: d3l243
--

ALTER DEFAULT PRIVILEGES FOR ROLE d3l243 IN SCHEMA mc REVOKE ALL ON TABLES  FROM d3l243;
ALTER DEFAULT PRIVILEGES FOR ROLE d3l243 IN SCHEMA mc GRANT SELECT ON TABLES  TO readaccess;

--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public REVOKE ALL ON TABLES  FROM postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT ON TABLES  TO readaccess;
