--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2
-- Dumped by pg_dump version 17.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: t_instrument_class; Type: TABLE DATA; Schema: public; Owner: d3l243
--

COPY public.t_instrument_class (instrument_class, is_purgeable, raw_data_type, requires_preparation, params, comment) FROM stdin;
AB_Sequencer	1	ab_sequencing_folder	0	\N	AB Next Gen Sequencer
Agilent_Ion_Trap	1	dot_d_folders	0	<sections><section name="DatasetQC"><item key="SaveTICAndBPIPlots" value="True" /><item key="SaveLCMS2DPlots" value="True" /><item key="ComputeOverallQualityScores" value="True" /><item key="CreateDatasetInfoFile" value="True" /><item key="LCMS2DPlotMZResolution" value="0.4" /><item key="LCMS2DPlotMaxPointsToPlot" value="200000" /><item key="LCMS2DPlotMinPointsPerSpectrum" value="2" /><item key="LCMS2DPlotMinIntensity" value="0" /><item key="LCMS2DOverviewPlotDivisor" value="10" /></section></sections>	.D directory with a DATA.MS file. Used by both Agilent LC-MS ion traps and Agilent GCs.
Agilent_TOF	0	dot_wiff_files	0	<sections><section name="DatasetQC"><item key="SaveTICAndBPIPlots" value="True" /><item key="SaveLCMS2DPlots" value="True" /><item key="ComputeOverallQualityScores" value="True" /><item key="CreateDatasetInfoFile" value="True" /><item key="LCMS2DPlotMZResolution" value="0.4" /><item key="LCMS2DPlotMaxPointsToPlot" value="200000" /><item key="LCMS2DPlotMinPointsPerSpectrum" value="2" /><item key="LCMS2DPlotMinIntensity" value="0" /><item key="LCMS2DOverviewPlotDivisor" value="10" /></section></sections>	\N
Agilent_TOF_V2	1	dot_d_folders	0	<sections><section name="DatasetQC"><item key="SaveTICAndBPIPlots" value="True" /><item key="SaveLCMS2DPlots" value="True" /><item key="ComputeOverallQualityScores" value="True" /><item key="CreateDatasetInfoFile" value="True" /><item key="LCMS2DPlotMZResolution" value="0.4" /><item key="LCMS2DPlotMaxPointsToPlot" value="200000" /><item key="LCMS2DPlotMinPointsPerSpectrum" value="2" /><item key="LCMS2DPlotMinIntensity" value="0" /><item key="LCMS2DOverviewPlotDivisor" value="10" /></section></sections>	.D directory with an AcqData subdirectory that has one or more .Bin files (for example MSScan.bin, MSPeak.bin, and MSProfile.bin) plus also a MSTS.xml file and a .m method directory
BrukerFTMS	1	zipped_s_folders	1	<sections><section name="DatasetQC"><item key="SaveTICAndBPIPlots" value="True" /><item key="SaveLCMS2DPlots" value="True" /><item key="ComputeOverallQualityScores" value="True" /><item key="CreateDatasetInfoFile" value="True" /><item key="LCMS2DPlotMZResolution" value="0.4" /><item key="LCMS2DPlotMaxPointsToPlot" value="200000" /><item key="LCMS2DPlotMinPointsPerSpectrum" value="2" /><item key="LCMS2DPlotMinIntensity" value="0" /><item key="LCMS2DOverviewPlotDivisor" value="10" /></section></sections>	Old 9T format
BrukerFT_BAF	1	bruker_ft	0	<sections><section name="DatasetQC"><item key="SaveTICAndBPIPlots" value="True" /><item key="SaveLCMS2DPlots" value="True" /><item key="ComputeOverallQualityScores" value="True" /><item key="CreateDatasetInfoFile" value="True" /><item key="LCMS2DPlotMZResolution" value="0.4" /><item key="LCMS2DPlotMaxPointsToPlot" value="200000" /><item key="LCMS2DPlotMinPointsPerSpectrum" value="2" /><item key="LCMS2DPlotMinIntensity" value="0" /><item key="LCMS2DOverviewPlotDivisor" value="10" /></section></sections>	.D directories that have .BAF files and ser or fid files; .m directory has apexAcquisition.method file; used on Bruker 9T, 12T, and 15T
BrukerMALDI_Imaging	1	bruker_maldi_imaging	0	<sections><section name="DatasetQC"><item key="SaveTICAndBPIPlots" value="True" /><item key="SaveLCMS2DPlots" value="True" /><item key="ComputeOverallQualityScores" value="True" /><item key="CreateDatasetInfoFile" value="True" /><item key="LCMS2DPlotMZResolution" value="0.4" /><item key="LCMS2DPlotMaxPointsToPlot" value="200000" /><item key="LCMS2DPlotMinPointsPerSpectrum" value="2" /><item key="LCMS2DPlotMinIntensity" value="0" /><item key="LCMS2DOverviewPlotDivisor" value="10" /></section></sections>	Series of zipped subdirectories, with names like 0_R00X329.zip; subdirectories inside the .Zip files have fid files
BrukerMALDI_Imaging_V2	1	bruker_ft	0	<sections><section name="DatasetQC"><item key="SaveTICAndBPIPlots" value="True" /><item key="SaveLCMS2DPlots" value="True" /><item key="ComputeOverallQualityScores" value="True" /><item key="CreateDatasetInfoFile" value="True" /><item key="LCMS2DPlotMZResolution" value="0.4" /><item key="LCMS2DPlotMaxPointsToPlot" value="200000" /><item key="LCMS2DPlotMinPointsPerSpectrum" value="2" /><item key="LCMS2DPlotMinIntensity" value="0" /><item key="LCMS2DOverviewPlotDivisor" value="10" /></section></sections>	.D directories that have a large ser file and large .mcf file; .m directory has apexAcquisition.method file
BrukerMALDI_Spot	1	bruker_maldi_spot	0	<sections><section name="DatasetQC"><item key="SaveTICAndBPIPlots" value="True" /><item key="SaveLCMS2DPlots" value="True" /><item key="ComputeOverallQualityScores" value="True" /><item key="CreateDatasetInfoFile" value="True" /><item key="LCMS2DPlotMZResolution" value="0.4" /><item key="LCMS2DPlotMaxPointsToPlot" value="200000" /><item key="LCMS2DPlotMinPointsPerSpectrum" value="2" /><item key="LCMS2DPlotMinIntensity" value="0" /><item key="LCMS2DOverviewPlotDivisor" value="10" /></section></sections>	Bruker TOF_TOF; directory has a .EMF file and a single subdirectory that has an acqu file and fid file
BrukerTOF_BAF	1	bruker_tof_baf	0	<sections><section name="DatasetQC"><item key="SaveTICAndBPIPlots" value="True" /><item key="SaveLCMS2DPlots" value="True" /><item key="ComputeOverallQualityScores" value="True" /><item key="CreateDatasetInfoFile" value="True" /><item key="LCMS2DPlotMZResolution" value="0.4" /><item key="LCMS2DPlotMaxPointsToPlot" value="200000" /><item key="LCMS2DPlotMinPointsPerSpectrum" value="2" /><item key="LCMS2DPlotMinIntensity" value="0" /><item key="LCMS2DOverviewPlotDivisor" value="10" /></section></sections>	.D directories from Maxis instrument; have .BAF files but no ser or fid file; .m directory has microTOFQMaxAcquisition.method file
BrukerTOF_TDF	1	bruker_tof_tdf	0	<sections><section name="DatasetQC"><item key="SaveTICAndBPIPlots" value="True" /><item key="SaveLCMS2DPlots" value="True" /><item key="ComputeOverallQualityScores" value="True" /><item key="CreateDatasetInfoFile" value="True" /><item key="LCMS2DPlotMZResolution" value="0.4" /><item key="LCMS2DPlotMaxPointsToPlot" value="200000" /><item key="LCMS2DPlotMinPointsPerSpectrum" value="2" /><item key="LCMS2DPlotMinIntensity" value="0" /><item key="LCMS2DOverviewPlotDivisor" value="10" /></section></sections>	.D directories from timsTOF instruments; have .tdf and .tdf_bin; .m directory has microTOFQImpacTemAcquisition.method
Bruker_Amazon_Ion_Trap	1	bruker_ft	0	<sections><section name="DatasetQC"><item key="SaveTICAndBPIPlots" value="True" /><item key="SaveLCMS2DPlots" value="True" /><item key="ComputeOverallQualityScores" value="True" /><item key="CreateDatasetInfoFile" value="True" /><item key="LCMS2DPlotMZResolution" value="0.4" /><item key="LCMS2DPlotMaxPointsToPlot" value="200000" /><item key="LCMS2DPlotMinPointsPerSpectrum" value="2" /><item key="LCMS2DPlotMinIntensity" value="0" /><item key="LCMS2DOverviewPlotDivisor" value="10" /></section></sections>	.D directories that have analysis.yep and extension.baf files; .m directory has EsquireAcquisition.Method file
Data_Folders	0	data_folders	0	\N	Used for Broker DB analysis jobs
FT_Booster_Data	1	data_folders	0	\N	Data from a TI PXIe system, combining thermo .raw files with Agilent FT data
Finnigan_FTICR	1	zipped_s_folders	1	<sections><section name="DatasetQC"><item key="SaveTICAndBPIPlots" value="True" /><item key="SaveLCMS2DPlots" value="True" /><item key="ComputeOverallQualityScores" value="True" /><item key="CreateDatasetInfoFile" value="True" /><item key="LCMS2DPlotMZResolution" value="0.4" /><item key="LCMS2DPlotMaxPointsToPlot" value="200000" /><item key="LCMS2DPlotMinPointsPerSpectrum" value="2" /><item key="LCMS2DPlotMinIntensity" value="0" /><item key="LCMS2DOverviewPlotDivisor" value="10" /></section></sections>	\N
Finnigan_Ion_Trap	1	dot_raw_files	0	<sections><section name="DatasetQC"><item key="SaveTICAndBPIPlots" value="True" /><item key="SaveLCMS2DPlots" value="True" /><item key="ComputeOverallQualityScores" value="True" /><item key="CreateDatasetInfoFile" value="True" /><item key="LCMS2DPlotMZResolution" value="0.4" /><item key="LCMS2DPlotMaxPointsToPlot" value="200000" /><item key="LCMS2DPlotMinPointsPerSpectrum" value="2" /><item key="LCMS2DPlotMinIntensity" value="0" /><item key="LCMS2DOverviewPlotDivisor" value="10" /></section></sections>	\N
GC_QExactive	1	dot_raw_files	0	<sections><section name="DatasetQC"><item key="SaveTICAndBPIPlots" value="True" /><item key="SaveLCMS2DPlots" value="True" /><item key="ComputeOverallQualityScores" value="True" /><item key="CreateDatasetInfoFile" value="True" /><item key="LCMS2DPlotMZResolution" value="0.4" /><item key="LCMS2DPlotMaxPointsToPlot" value="200000" /><item key="LCMS2DPlotMinPointsPerSpectrum" value="2" /><item key="LCMS2DPlotMinIntensity" value="0" /><item key="LCMS2DOverviewPlotDivisor" value="10" /></section></sections>	\N
IMS_Agilent_TOF_DotD	1	dot_uimf_files	0	<sections><section name="DatasetQC"><item key="SaveTICAndBPIPlots" value="True" /><item key="SaveLCMS2DPlots" value="True" /><item key="ComputeOverallQualityScores" value="True" /><item key="CreateDatasetInfoFile" value="True" /><item key="LCMS2DPlotMZResolution" value="0.4" /><item key="LCMS2DPlotMaxPointsToPlot" value="200000" /><item key="LCMS2DPlotMinPointsPerSpectrum" value="2" /><item key="LCMS2DPlotMinIntensity" value="0" /><item key="LCMS2DOverviewPlotDivisor" value="10" /></section></sections>	Data is acquired natively as .D directories, which are then converted to .UIMF files
IMS_Agilent_TOF_UIMF	1	dot_uimf_files	0	<sections><section name="DatasetQC"><item key="SaveTICAndBPIPlots" value="True" /><item key="SaveLCMS2DPlots" value="True" /><item key="ComputeOverallQualityScores" value="True" /><item key="CreateDatasetInfoFile" value="True" /><item key="LCMS2DPlotMZResolution" value="0.4" /><item key="LCMS2DPlotMaxPointsToPlot" value="200000" /><item key="LCMS2DPlotMinPointsPerSpectrum" value="2" /><item key="LCMS2DPlotMinIntensity" value="0" /><item key="LCMS2DOverviewPlotDivisor" value="10" /></section></sections>	Data is acquired natively as .UIMF files
IMS_Biospect_TOF	0	biospec_folder	0	<sections><section name="DatasetQC"><item key="SaveTICAndBPIPlots" value="True" /><item key="SaveLCMS2DPlots" value="True" /><item key="ComputeOverallQualityScores" value="True" /><item key="CreateDatasetInfoFile" value="True" /><item key="LCMS2DPlotMZResolution" value="0.4" /><item key="LCMS2DPlotMaxPointsToPlot" value="200000" /><item key="LCMS2DPlotMinPointsPerSpectrum" value="2" /><item key="LCMS2DPlotMinIntensity" value="0" /><item key="LCMS2DOverviewPlotDivisor" value="10" /></section></sections>	Unused
IMS_Sciex_TOF	0	dot_wiff_files	0	<sections><section name="DatasetQC"><item key="SaveTICAndBPIPlots" value="True" /><item key="SaveLCMS2DPlots" value="True" /><item key="ComputeOverallQualityScores" value="True" /><item key="CreateDatasetInfoFile" value="True" /><item key="LCMS2DPlotMZResolution" value="0.4" /><item key="LCMS2DPlotMaxPointsToPlot" value="200000" /><item key="LCMS2DPlotMinPointsPerSpectrum" value="2" /><item key="LCMS2DPlotMinIntensity" value="0" /><item key="LCMS2DOverviewPlotDivisor" value="10" /></section></sections>	Unused
Illumina_Sequencer	1	illumina_folder	0		.txt.gz fastq file
LCMSNet_LC	0	lcmsnet_lcmethod	0	\N	LCMSNet LC with no other pump data file
LTQ_FT	1	dot_raw_files	0	<sections><section name="DatasetQC"><item key="SaveTICAndBPIPlots" value="True" /><item key="SaveLCMS2DPlots" value="True" /><item key="ComputeOverallQualityScores" value="True" /><item key="CreateDatasetInfoFile" value="True" /><item key="LCMS2DPlotMZResolution" value="0.4" /><item key="LCMS2DPlotMaxPointsToPlot" value="200000" /><item key="LCMS2DPlotMinPointsPerSpectrum" value="2" /><item key="LCMS2DPlotMinIntensity" value="0" /><item key="LCMS2DOverviewPlotDivisor" value="10" /></section></sections>	
PrepHPLC	1	dot_d_folders	0	\N	.D directories that have several .Reg files, a Run.Log file, and a SAMPLE.MAC file
QStar_QTOF	0	dot_wiff_files	0	<sections><section name="DatasetQC"><item key="SaveTICAndBPIPlots" value="True" /><item key="SaveLCMS2DPlots" value="True" /><item key="ComputeOverallQualityScores" value="True" /><item key="CreateDatasetInfoFile" value="True" /><item key="LCMS2DPlotMZResolution" value="0.4" /><item key="LCMS2DPlotMaxPointsToPlot" value="200000" /><item key="LCMS2DPlotMinPointsPerSpectrum" value="2" /><item key="LCMS2DPlotMinIntensity" value="0" /><item key="LCMS2DOverviewPlotDivisor" value="10" /></section></sections>	\N
Sciex_QTrap	1	sciex_wiff_files	0	<sections><section name="DatasetQC"><item key="SaveTICAndBPIPlots" value="True" /><item key="SaveLCMS2DPlots" value="True" /><item key="ComputeOverallQualityScores" value="True" /><item key="CreateDatasetInfoFile" value="True" /><item key="LCMS2DPlotMZResolution" value="0.4" /><item key="LCMS2DPlotMaxPointsToPlot" value="200000" /><item key="LCMS2DPlotMinPointsPerSpectrum" value="2" /><item key="LCMS2DPlotMinIntensity" value="0" /><item key="LCMS2DOverviewPlotDivisor" value="10" /></section></sections>	AB Sciex QTrap.  Each dataset has a .wiff file and a .wiff.scan file.
Sciex_TripleTOF	1	dot_mzml_files	0	<sections><section name="DatasetQC"><item key="SaveTICAndBPIPlots" value="True" /><item key="SaveLCMS2DPlots" value="True" /><item key="ComputeOverallQualityScores" value="True" /><item key="CreateDatasetInfoFile" value="True" /><item key="LCMS2DPlotMZResolution" value="0.4" /><item key="LCMS2DPlotMaxPointsToPlot" value="200000" /><item key="LCMS2DPlotMinPointsPerSpectrum" value="2" /><item key="LCMS2DPlotMinIntensity" value="0" /><item key="LCMS2DOverviewPlotDivisor" value="10" /></section></sections>	AB Sciex TripleTOF.  Original data converted to .mzML format
Shimadzu_GC	1	dot_qgd_files	0	\N	\N
Thermo_Exactive	1	dot_raw_files	0	<sections><section name="DatasetQC"><item key="SaveTICAndBPIPlots" value="True" /><item key="SaveLCMS2DPlots" value="True" /><item key="ComputeOverallQualityScores" value="True" /><item key="CreateDatasetInfoFile" value="True" /><item key="LCMS2DPlotMZResolution" value="0.4" /><item key="LCMS2DPlotMaxPointsToPlot" value="200000" /><item key="LCMS2DPlotMinPointsPerSpectrum" value="2" /><item key="LCMS2DPlotMinIntensity" value="0" /><item key="LCMS2DOverviewPlotDivisor" value="10" /></section></sections>	\N
Thermo_SII_LC	1	dot_raw_files	0	<sections><section name="DatasetQC"><item key="SaveTICAndBPIPlots" value="True" /><item key="CreateDatasetInfoFile" value="True" /></section></sections>	SII - Standard Instrument Integration, allows controlling Chromeleon-supported LC modules from Xcalibur
Triple_Quad	1	dot_raw_files	0	<sections><section name="DatasetQC"><item key="SaveTICAndBPIPlots" value="True" /><item key="SaveLCMS2DPlots" value="True" /><item key="ComputeOverallQualityScores" value="True" /><item key="CreateDatasetInfoFile" value="True" /><item key="LCMS2DPlotMZResolution" value="0.4" /><item key="LCMS2DPlotMaxPointsToPlot" value="200000" /><item key="LCMS2DPlotMinPointsPerSpectrum" value="2" /><item key="LCMS2DPlotMinIntensity" value="0" /><item key="LCMS2DOverviewPlotDivisor" value="10" /></section></sections>	\N
Waters_Acquity_LC	1	dot_raw_folder	0	<sections><section name="DatasetQC"><item key="SaveTICAndBPIPlots" value="True" /><item key="CreateDatasetInfoFile" value="True" /></section></sections>	
Waters_IMS	1	dot_raw_folder	0	\N	Waters Synapt TWIMS
Waters_TOF	0	dot_raw_folder	0	<sections><section name="DatasetQC"><item key="SaveTICAndBPIPlots" value="True" /><item key="SaveLCMS2DPlots" value="True" /><item key="ComputeOverallQualityScores" value="True" /><item key="CreateDatasetInfoFile" value="True" /><item key="LCMS2DPlotMZResolution" value="0.4" /><item key="LCMS2DPlotMaxPointsToPlot" value="200000" /><item key="LCMS2DPlotMinPointsPerSpectrum" value="2" /><item key="LCMS2DPlotMinIntensity" value="0" /><item key="LCMS2DOverviewPlotDivisor" value="10" /></section></sections>	\N
timsTOF_MALDI_Imaging	1	bruker_tof_tsf	0	<sections><section name="DatasetQC"><item key="SaveTICAndBPIPlots" value="True" /><item key="SaveLCMS2DPlots" value="True" /><item key="ComputeOverallQualityScores" value="True" /><item key="CreateDatasetInfoFile" value="True" /><item key="LCMS2DPlotMZResolution" value="0.4" /><item key="LCMS2DPlotMaxPointsToPlot" value="200000" /><item key="LCMS2DPlotMinPointsPerSpectrum" value="2" /><item key="LCMS2DPlotMinIntensity" value="0" /><item key="LCMS2DOverviewPlotDivisor" value="10" /></section></sections>	Dataset directory with multiple .D directories that each have analysis.tsf
\.


--
-- PostgreSQL database dump complete
--

